# VECTORIZATION

In [2]:
import numpy as np
arr= np.zeros((2,10))
arr + 10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [3]:
# ADDING TWO ARRAYS 
arr2 = np.ones((2,10))
arr + arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
# ADDING TWO LIST
L1 = [1,2,4,5]
L2 = [3,4,6,7]
sum = []
for i,_ in enumerate(L1):
    sum.append(L1[i]+L2[i])
print(sum)

[4, 6, 10, 12]


# WHERE METHOD IN NUMPY

In [7]:
# CHECKING WHO IS FAIL OR NOT BY APPLYNG CONDITION MARKS >=50 = PASS OTHERWISE FAIL
marks = np.array([75,9,50,80,90])
np.where(marks>=50,"PASS","FAIL")

array(['PASS', 'FAIL', 'PASS', 'PASS', 'PASS'], dtype='<U4')

In [8]:
#INCREMENT ON SALARY  IF SALARY LESS THAN 50 INCREMENT 1.1% OTHERWISE INCREMENT 1.05%
salary = np.array([10,70,880,50,30])
np.where(salary<50,salary*1.1,salary*1.05)

array([ 11. ,  73.5, 924. ,  52.5,  33. ])

In [9]:
# CHECKING DATA TYPE
marks.dtype

dtype('int32')

# TRANSPOSE

In [10]:
# making an array having 1 to 100 numbers then reshape it by 10 rows and 10 coukumns
arr= np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [11]:
# APPLYING TRANSPOSE BY USING 'T'
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [13]:
# APPLYING TRANSPOSE BY USING 'TRANSPOSE'
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

# MEAN

In [14]:
arr = np.array([1,3,4,5,2])
arr.mean()

3.0

# CUMULATIVE SUM(cumsum)

In [15]:
arr = np.array([1,3,4,5,2])
arr.cumsum()

array([ 1,  4,  8, 13, 15], dtype=int32)

# CUMULATIVE PRODUCT(cumprod)

In [16]:
arr = np.array([1,3,4,5,2])
arr.cumprod()

array([  1,   3,  12,  60, 120], dtype=int32)

# METHODS FOR BOOLEAN ARRAYS

In [21]:
# only getting values of male 
gender = np.array(['MALE','FEMALE','MALE','MALE','MALE'])
gender[gender=='MALE']

array(['MALE', 'MALE', 'MALE', 'MALE'], dtype='<U6')

In [27]:
# get values of male in terms of true and false true for mal
arr = gender == 'MALE'
arr

array([ True, False,  True,  True,  True])

In [28]:
# checking how many time true value ocurse mean male occurs 
arr.sum() 

4

In [30]:
# checking how many time true value ocurse mean female occurs here we apply condition for female
arr = gender== 'FEMALE'
arr.sum()

1

In [31]:
# cheking female occurs atleast one time in array (EXISTENTIAL QUANTIFIER) ----->ANY
arr= gender =='FEMALE'
arr.any()

True

In [32]:
# checking  all elements array are female or not (UNIVERSAL QUANTIFIER)----> ALL
arr= gender =='FEMALE'
arr.all()

False

In [35]:
arr=np.array([2,4,10,20,16])
x = arr%2==0 # checking even values in array
x

array([ True,  True,  True,  True,  True])

In [36]:
x.all()

True

# SORTING

In [38]:
arr = np.array([2,4,10,20,16])
arr.sort()
arr

array([ 2,  4, 10, 16, 20])

In [40]:
# DESCENDING
arr[::-1]

array([20, 16, 10,  4,  2])

# UNIQUE

In [48]:
arr= np.array([1,2,4,1,6,2])
u = np.unique(arr)
u

array([1, 2, 4, 6])

# FILE INPUT OUTPUT

In [49]:
# FOR SAVING 1 ARRAY IN FILE
np.save('data',u)

In [50]:
# LOADING FILE
content = np.load('data.npy')
content

array([1, 2, 4, 6])

In [51]:
# SAVING MULTIPLE ARRAYS IN 1 FILE ,THIS TIME WE SAVE 2 ARRAYS IN 1 FILE
students = np.array(['ALI','ASAD','AHMED'])
marks = np.array([30,20,60])
#SAVING ARRAYS IN FILE
np.savez('ARRAYS',std=students,m = marks)

In [52]:
# LOADING FILE 
results = np.load('ARRAYS.npz')
results['std']

array(['ALI', 'ASAD', 'AHMED'], dtype='<U5')

In [53]:
results['m']

array([30, 20, 60])

# LINEAR ALGEBRA FUNCTION

In [57]:
from numpy import linalg

In [58]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
# FINDING DIAGONAL VALUES ONLY
arr.diagonal()

array([ 0,  5, 10, 15])

In [61]:
# SUM OF DIAGONAL ELEMNTS
arr.trace()

30

In [63]:
#CREATING NEW ARRAY
arr1 = np.arange(10,26).reshape((4,4))
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [64]:
# MULTIPLYING TWO ARRAYS USING DOT FUNCTION
arr.dot(arr1)

array([[ 116,  122,  128,  134],
       [ 372,  394,  416,  438],
       [ 628,  666,  704,  742],
       [ 884,  938,  992, 1046]])

In [67]:
# FINDING DETERMINANT
linalg.det(arr)

-2.9582283945787796e-30

In [68]:
# FINDING VARIANCE INFO OF MATRIX
linalg.eig(arr)

(array([ 3.24642492e+01, -2.46424920e+00,  4.52933966e-17, -1.52275132e-15]),
 array([[-0.11417645, -0.7327781 ,  0.01936986, -0.48846795],
        [-0.3300046 , -0.28974835,  0.38216644,  0.83598112],
        [-0.54583275,  0.15328139, -0.82244247, -0.20655839],
        [-0.76166089,  0.59631113,  0.42090617, -0.14095478]]))

In [70]:
# FINDING INVERSE OF MATRIX
linalg.inv(np.array([[1,5],[9,8]]))

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [71]:
# breaking 1 matrix into 2 pieces 1st part is 'q' secong part is r
linalg.qr(arr)

(array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
        [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
        [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
        [-0.80178373,  0.23904572,  0.12966702,  0.53215267]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
         -5.12511879e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.82043219e-16]]))

In [72]:
# breaking 1 matrix in to 3 pecies ,1st part = l,2nd part = u,3rd part = r
linalg.svd(arr)

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
        [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
        [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
        [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]),
 array([3.51399637e+01, 2.27661021e+00, 8.80118491e-16, 4.41188001e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
        [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]]))

# PSEUDO RANDOM NUMBER GENERATION
#### NORMAL()
#### SEED()
#### GAMMA()
#### UNIFORM()

In [74]:
# NORMAL DISTRIBUTION
np.random.normal(3,4,(3,3))

array([[ 1.77567311,  3.04614277,  8.43957528],
       [ 8.89311645,  8.26228976, -1.45135213],
       [ 0.93626586,  6.39001578,  2.71536112]])

In [75]:
# GAMMA DISTRIBUTION
np.random.gamma(1,2,(4,4))

array([[0.81221982, 7.34088634, 3.9315646 , 1.33523564],
       [1.45491072, 1.7429958 , 1.16043504, 0.15098835],
       [1.04229223, 9.16730872, 0.6633487 , 1.17974876],
       [1.67269206, 0.5949608 , 0.56581901, 2.1719964 ]])

In [78]:
# SEED DISTRIBUTION
np.random.seed(5)
np.random.rand()

0.22199317108973948

In [79]:
# UNIFORM DISTRIBUTION
np.random.uniform(1,5,(3,4))

array([[4.48292922, 1.82687662, 4.67444363, 2.95364476],
       [3.44697545, 4.06363143, 3.07367195, 2.18720201],
       [1.75088491, 1.32296508, 3.95376118, 2.76523689]])

# RESHAPE

In [80]:
arr = np.arange(16)
arr.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [81]:
# RESHAPE COLUMN WISE  COLUMN = F
arr = np.arange(16)
arr.reshape((4,4),order = 'F')

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [87]:
# RESHAPE ROW WISE ROW = C
arr.reshape((4,4),order = 'C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# CONVERTING IN TO 1D ARRAY
#### 1. FLATTEN
#### 2. RAVEL
###### Flatten always produces a one-dimensional copy, whereas ravel attempts to provide a one-dimensional view of 
###### the original matrix.

In [83]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
arr.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# CONCATENATE

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])

In [92]:
a

array([[1, 2],
       [3, 4]])

In [93]:
b

array([[ 7,  8],
       [ 9, 10]])

### 1ST METHOD

In [95]:
# CONCATENATE ROW WISE (AXIS = O) = ROW 
np.concatenate((a,b),axis= 0)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [96]:
# CONCATENATE COLUMN WISE (AXIS = 1) = COLUMN 
np.concatenate((a,b),axis= 1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [97]:
a = np.array([[1,7,9],[2,3,4],[5,6,7]])
b = np.array([[9,4,9],[2,3,2],[0,6,7]])

In [98]:
a

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7]])

In [99]:
b

array([[9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [100]:
# CONCATENATE ROW WISE (AXIS = O) = ROW 
np.concatenate((a,b),axis= 0)

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [101]:
# CONCATENATE COLUMN WISE (AXIS = 1) = COLUMN 
np.concatenate((a,b),axis= 1)

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

### 2ND METHOD

In [102]:
# CONCATENATE ROW WISE (vstack) = ROW 
np.vstack((a,b))

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [104]:
# CONCATENATE COLUMN WISE (hstack) = COLUMN 
np.hstack((a,b))


array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

### 3RD METHOD

In [105]:
# CONCATENATE ROW WISE (r_) = ROW 
np.r_[a,b]

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [106]:
# CONCATENATE COLUMN WISE (c_) = COLUMN 
np.c_[a,b]


array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

# SPLITTING ARRAY

In [107]:
# BREAKING ARRAY IN TO TWO PARTS 
x = np.array([1,9,9,7,1,2,3])
np.split(x,[3])

[array([1, 9, 9]), array([7, 1, 2, 3])]

In [108]:
# BREAKING ARRAY IN TO THREE PARTS 
x = np.array([1,9,9,7,1,2,3])
np.split(x,[3,5])

[array([1, 9, 9]), array([7, 1]), array([2, 3])]

In [113]:
# BREAKING BY USING SLICING METHOD
l = np.arange(0,7,2)
print(l)  # these are the splitting points
np.split(x,l)


[0 2 4 6]


[array([], dtype=int32),
 array([1, 9]),
 array([9, 7]),
 array([1, 2]),
 array([3])]

In [115]:
x = np.array([[1,3],[2,4]])
x

array([[1, 3],
       [2, 4]])

In [116]:
np.split(x,[1]) #  1 means row number 1 

[array([[1, 3]]), array([[2, 4]])]