# COMPARISON BETWWEN NUMPY ARRAY AND PYTHON LIST

In [1]:
# PYTHON LIST 
python_list = range(1000000)
%time for i in range(10):results=[i*5 for i in python_list]

CPU times: total: 938 ms
Wall time: 931 ms


In [2]:
# NUMPY ARRAY
import numpy as np 
numpy_array = np.arange(1000000)
%time for i in range(10):results=numpy_array*5 

CPU times: total: 15.6 ms
Wall time: 26 ms


********       SO THE NUMPY ARRAY IS MORE EFFICIENT IN TIME THAN PYTHON LIST 
BECAUSE PYTHON LIST TAKES 853 MS FOR
EXECUTION AND NUMPY ARRAY TAKES 18.2 MS       *********
    

# NUMPY ARRAY CREATION METHODS 

In [3]:
# 1D ARRAY  HAVING ONLY ZEROS
one_d_array = np.zeros((10))
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 1D ARRAY  HAVING ONLY ONES
one_d_array = np.ones((10))
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 1D ARRAY  HAVING ONLY TWO'S
# *********** 1st method *************
one_d_array = np.ones((10))
one_d_array * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
# 1D ARRAY  HAVING ONLY TWO'S
# *********** 2nd method *************
one_d_array = np.zeros((10))
one_d_array + 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [7]:
# 1D ARRAY  HAVING 1 TO 10 VALUES
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# 2D ARRAY HAVING ZEROS
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# 3D ARRAY HAVING ZEROS
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [10]:
# 4D ARRAY HAVING ZEROS
np.zeros((2,2,5,3)) 

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [11]:
# 3D ARRAY HAVING FIVE'S ONLY 
np.zeros((3,2,5)) +5

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [12]:
x = np.array([1,3,7,9,10,16,78,18])
x

array([ 1,  3,  7,  9, 10, 16, 78, 18])

In [13]:
x.shape

(8,)

In [14]:
x.reshape((2,4))

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [15]:
y = x.reshape((2,4))
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [16]:
y.ndim

2

# ACCESSING INDIVIDAL ELEMENTS FROM 2D ARRAY

In [17]:
y[0,3]

9

In [18]:
y[1,2]

78

# ACCESSING INDIVIDAL ELEMENTS FROM 2D ARRAY

In [19]:
z = y.reshape((2,2,2))
z

array([[[ 1,  3],
        [ 7,  9]],

       [[10, 16],
        [78, 18]]])

In [20]:
z[0,1,1] # accessing 9 from 3D array

9

# SLICING

In [21]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [22]:
y = y.reshape(4,2)
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [23]:
y[0:3]

array([[ 1,  3],
       [ 7,  9],
       [10, 16]])

In [24]:
y[::2]


array([[ 1,  3],
       [10, 16]])

# SLICING AND INDEXING

In [25]:
y[0:3,1]

array([ 3,  9, 16])

In [26]:
y[::,0]

array([ 1,  7, 10, 78])

# FANCY INDEXING

In [27]:
x[[3,5]]

array([ 9, 16])

# VECTORIZED OPERATIONS

In [28]:
x = np.array([1,5,7])
y = np.array([3,2,9])

In [29]:
x+y

array([ 4,  7, 16])

In [30]:
x-y

array([-2,  3, -2])

In [31]:
x*y

array([ 3, 10, 63])

In [32]:
x/y

array([0.33333333, 2.5       , 0.77777778])

In [33]:
1/x

array([1.        , 0.2       , 0.14285714])

In [34]:
x*y**2

array([  9,  20, 567])

# MAKE THIS SHAPE 
###### 00000
###### 11111
###### 11111
###### 11111
###### 00000


In [35]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
arr[0]=0
arr[-1]=0

In [37]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

# MAKE THIS SHAPE 
###### 00000
###### 01110
###### 01110
###### 01110
###### 00000

In [38]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
arr[1,1:4]=1
arr[2,1:4]=1
arr[3,1:4]=1  
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
arr[1:-1,1:-1]
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# MAKE THIS SHAPE 
###### 01010101
###### 10101010
###### 01010101
###### 10101010
###### 01010101
###### 10101010
###### 01010101
###### 10101010

In [64]:
arr = np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
arr[0,::-2]=1
arr[2,::-2]=1
arr[4,::-2]=1
arr[6,::-2]=1
arr[1,::2]=1
arr[3,::2]=1
arr[5,::2]=1
arr[7,::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# MAKE THIS SHAPE 
###### 00000
###### 11111
###### 00000
###### 11111
###### 00000
###### 11111


In [68]:
arr = np.zeros((6,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
arr[1,::]=1
arr[3,::]=1
arr[5,::]=1
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

# MAKE THIS SHAPE 
###### 01110
###### 10101
###### 11011
###### 10101
###### 01110


In [91]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
arr[0,1:-1]=1
arr[1,::2]=1
arr[2,0:2]=1
arr[2,3:5]=1
arr[3,::2]=1
arr[4,1:-1]=1
arr

array([[0., 1., 1., 1., 0.],
       [1., 0., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [43]:
np.empty((6,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# COMPARISON BETWEEN MATRICES

In [44]:
salary = np.array([10,25,5,2])
salary > 5

array([ True,  True, False, False])

In [45]:
salary = np.array([10,25,5,2])
salary [salary > 5]

array([10, 25])

# NUMPY ELEMENT-WISE FUNCTIONS

In [46]:
nums = [10,20,45,35,67,89,12,23]
np.sin(nums)

array([-0.54402111,  0.91294525,  0.85090352, -0.42818267, -0.85551998,
        0.86006941, -0.53657292, -0.8462204 ])

In [47]:
nums = [10,20,45,35,67,89,12,23]
np.cos(nums)

array([-0.83907153,  0.40808206,  0.52532199, -0.90369221, -0.5177698 ,
        0.51017704,  0.84385396, -0.53283302])

In [48]:
np.tan(nums)

array([ 0.64836083,  2.23716094,  1.61977519,  0.47381472,  1.65231726,
        1.68582537, -0.63585993,  1.58815308])

In [49]:
np.sqrt(nums)

array([3.16227766, 4.47213595, 6.70820393, 5.91607978, 8.18535277,
       9.43398113, 3.46410162, 4.79583152])

In [50]:
np.square(nums)

array([ 100,  400, 2025, 1225, 4489, 7921,  144,  529], dtype=int32)

In [51]:
np.abs(nums)

array([10, 20, 45, 35, 67, 89, 12, 23])

In [52]:
np.fabs(nums)

array([10., 20., 45., 35., 67., 89., 12., 23.])

In [53]:
np.exp(nums)

array([2.20264658e+04, 4.85165195e+08, 3.49342711e+19, 1.58601345e+15,
       1.25236317e+29, 4.48961282e+38, 1.62754791e+05, 9.74480345e+09])